extends RefCounted

static func build() -> RS_InputProfile:
	var builder := U_InputProfileBuilder.new()
	builder.named("input.profile.accessibility_gamepad.name")
	builder.with_device_type(1)
	builder.with_description("input.profile.accessibility_gamepad.description")
	builder.bind_joypad_motion("move_forward", JOY_AXIS_LEFT_Y, -1.0)
	builder.bind_joypad_motion("move_backward", JOY_AXIS_LEFT_Y, 1.0)
	builder.bind_joypad_motion("move_left", JOY_AXIS_LEFT_X, -1.0)
	builder.bind_joypad_motion("move_right", JOY_AXIS_LEFT_X, 1.0)
	builder.bind_joypad_button("jump", JOY_BUTTON_A)
	builder.bind_joypad_button("sprint", JOY_BUTTON_LEFT_STICK)
	builder.bind_joypad_button("interact", JOY_BUTTON_X)
	builder.bind_joypad_button("camera_center", JOY_BUTTON_RIGHT_STICK)
	builder.bind_joypad_button("ui_up", JOY_BUTTON_DPAD_UP)
	builder.bind_joypad_button("ui_down", JOY_BUTTON_DPAD_DOWN)
	builder.bind_joypad_button("ui_left", JOY_BUTTON_DPAD_LEFT)
	builder.bind_joypad_button("ui_right", JOY_BUTTON_DPAD_RIGHT)
	builder.bind_joypad_motion("look_up", JOY_AXIS_RIGHT_Y, -1.0)
	builder.bind_joypad_motion("look_down", JOY_AXIS_RIGHT_Y, 1.0)
	builder.bind_joypad_motion("look_left", JOY_AXIS_RIGHT_X, -1.0)
	builder.bind_joypad_motion("look_right", JOY_AXIS_RIGHT_X, 1.0)
	builder.with_accessibility(0.2, true, 0.0)
	return builder.build()
